AWSTemplateFormatVersion: '2010-09-09'
Description: ImageBuilder Component to install AWS PCS Slurm

### Stack metadata
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Installer Parameters
        Parameters:
          - SlurmVersion
          - PcsSlurmInstallerVersion
      - Label:
          default: HPC Recipes Configuration
        Parameters:
          - HpcRecipesS3Bucket
          - HpcRecipesBranch

Parameters:
  SlurmVersion:
    Type: String
    Default: '25.05'
    Description: Major version of Slurm to install
    AllowedValues:
         - '24.05'
         - '24.11'
         - '25.05'
  PcsSlurmInstallerVersion:
    Type: String
    Default: latest
    Description: Version of the PCS Slurm installer to use
    AllowedPattern: '^(latest|[0-9]+)$'
  HpcRecipesS3Bucket:
    Type: String
    Default: aws-hpc-recipes
    Description: HPC Recipes for AWS S3 bucket
    AllowedValues:
         - aws-hpc-recipes
         - aws-hpc-recipes-dev
  HpcRecipesBranch:
    Type: String
    Default: main
    Description: HPC Recipes for AWS release branch
    AllowedPattern: '^(?!.*/\.git$)(?!.*/\.)(?!.*\\.\.)[a-zA-Z0-9-_\.]+$'

Resources:
  PcsSlurmInstaller:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: !Sub 'PcsSlurmInstaller-${AWS::StackName}'
      Description: Download and install Slurm for AWS PCS
      Version: '0.0.1'
      Platform: Linux
      Data: !Sub |
        name: 'AWS PCS Slurm installer'
        schemaVersion: 1.0
        parameters:
          - PcsSlurmVersion:
              type: string
              description: 'Major version of Slurm to install'
              default: '${SlurmVersion}'
          - PcsSlurmInstallerVersion:
              type: string
              description: 'Version of the AWS PCS Slurm installer to use'
              default: '${PcsSlurmInstallerVersion}'
        phases:
          - name: build
            steps:
              - name: DownloadInstaller
                action: WebDownload
                inputs:
                  - source: https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/scripts/install-pcs-slurm.sh
                    destination: install-pcs-slurm.sh
              - name: InstallSlurm
                action: ExecuteBash
                inputs:
                  commands:
                    - set -e
                    - 'chmod +x install-pcs-slurm.sh'
                    - './install-pcs-slurm.sh --aws-region=${AWS::Region} --pcs-slurm-version={{ PcsSlurmVersion }} --pcs-slurm-installer-version={{ PcsSlurmInstallerVersion }}'

Outputs:
  ImageBuilderComponent:
    Value: !Ref PcsSlurmInstaller
