Description: All-in-one deployment to support multi-user AWS PCS.

Parameters:

  DirectoryName:
    Description: Domain name
    Type: String
    Default: corp.example.com
    # TODO - This is constrained until we can guarantee the downstream bits work with other domain names
    AllowedValues:
      - corp.example.com

  VpcId:
    Description: VPC where AD will be created.
    Type: AWS::EC2::VPC::Id

  SubnetIds:
    Description: Select two subnet(s) for AD servers in different AZs. Private subnets are recommended. 
    Type: List<AWS::EC2::Subnet::Id>

  Keypair:
    Description: EC2 Keypair to access the AD management instance.
    Type: AWS::EC2::KeyPair::KeyName
    Default: ""

  ClientIpCidr:
    Description: IP(s) allowed to directly access the AD management instance. We recommend that you restrict it with your own IP/subnet (x.x.x.x/32 for your own ip or x.x.x.x/24 for range. Replace x.x.x.x with your own PUBLIC IP. You can get your public IP using tools such as https://ifconfig.co/)
    Default: 0.0.0.0/0
    Type: String
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Value must be a valid IP or network range of the form x.x.x.x/x.

  ClientPrefixList:
    Description: (Optional) VPC Prefix List controlling access to the AD management instance. 
    Default: ""
    Type: String
    AllowedPattern: ^(pl-[a-z0-9]{8,20})?$
    ConstraintDescription: Must be a valid VPC Prefix List ID, which begins with `pl-` or be empty.

  SssdConfigTemplateS3Path:
    Description: An S3 Path (without the s3://) to a configuration file template for configuring SSSD. 
    Type: String
    Default: aws-hpc-recipes-dev/pcs/recipes/pcs/multiuser_demo/assets/sssd.conf.template.mad

  # SecretsPrefix:
  #   Description: Prefix for naming configuration secrets in AWS Secrets Manager
  #   Type: String
  #   Default: HPC
  #   ^([A-Za-z0-9]{3,12})?$

Resources:

  DirectoryService:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DomainName: !Ref DomainName
        SubDomain: ""
        ServiceAccountName: ServiceAccount
        LDIFS3Path: !Ref LDIFS3Path
        Keypair: !Ref Keypair
        UserName: ""
        UserPassword: ""
        AllowedIps: !Ref ClientIpCidr
        ClientPrefixList: !Ref ClientPrefixList
        # StopAdAdminInstance: !Ref StopAdAdminInstances
        Vpc: !GetAtt [ Networking, Outputs.VPC ]
        PrivateSubnetOne: {"Fn::Select": [0, { "Fn::Split" : [",", !GetAtt [ Networking, Outputs.PrivateSubnets ]] }]}
        PrivateSubnetTwo: {"Fn::Select": [1, { "Fn::Split" : [",", !GetAtt [ Networking, Outputs.PrivateSubnets ]] }]}
      TemplateURL: https://aws-hpc-recipes.s3.us-east-1.amazonaws.com/main/recipes/dir/demo_managed_ad/assets/main.yaml

Outputs:
