AWSTemplateFormatVersion: 2010-09-09
Description: IAM instance profile for use with PCS compute node groups

Parameters:

  SssdConfigTemplateS3Path:
    Description: An S3 Path (without the s3://) to a configuration file template for configuring SSSD. 
    Type: String
    Default: awspcs-hpc-recipes-demo/sssd.conf.template

  SecretsPrefix:
    Description: Prefix for naming configuration secrets in AWS Secrets Manager
    Type: String
    Default: HPC
    AllowedPattern: ^([A-Za-z0-9]{3,12})?$

Resources:

  PcsInstanceIamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "PcsAdConfiguration-${AWS::StackName}"
      Description: "AWS IAM role PCS node group instances with AD support"
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
           - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
           - "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
           - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - pcs:RegisterComputeNodeGroupInstance
                Effect: Allow
                Resource: "*"
          PolicyName: PcsRegisterCngInstance
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - s3:getObject
                Effect: Allow
                Resource: !Sub 
                  - "arn:${AWS::Partition}:s3:::${S3Path}"
                  - S3Path: !Ref SssdConfigTemplateS3Path
          PolicyName: GetSsdConfigTemplate
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - secretsmanager:GetResourcePolicy
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                  - secretsmanager:ListSecretVersionIds
                Effect: Allow
                Resource: !Sub 
                  - "arn:${AWS::Partition}:secretsmanager:*:*:secret:${SecretsPrefix}-"
                  - SecretsPrefix: !Ref SecretsPrefix
          PolicyName: GetSsdConfigSecrets

  PcsInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
            - !Ref PcsInstanceIamRole
      InstanceProfileName: !Sub "PcsAdConfiguration-${AWS::StackName}"

Outputs:
  InstanceProfile:
    Value: !Ref PcsInstanceProfile
  InstanceProfileArn:
    Value: !GetAtt PcsInstanceProfile.Arn

