AWSTemplateFormatVersion: 2010-09-09
Description: Create a launch template for AWS PCS supporting a shared /home filesystem and optional /shared filesystem.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Launch Template
        Parameters:
          - LaunchTemplateName
      - Label:
          default: Security groups
        Parameters:
          - NodeGroupSecurityGroupIds
      - Label:
          default: Filesystems (/home and optional /shared)
        Parameters:
          - EfsFilesystemId
          - FSxLustreFilesystemId
          - FSxLustreFilesystemMountName

Parameters:

  LaunchTemplateName:
    Type: String
    Default: "AWSPCS-getting-started-lt"
    Description: Launch template name
  NodeGroupSecurityGroupIds:
      Type: List<AWS::EC2::SecurityGroup::Id>
      Description: Security group(s).
  EfsFilesystemId:
    Type: String
    Description: Amazon EFS Filesystem ID
  FSxLustreFilesystemId:
    Type: String
    Description: (Optional) Amazon FSx for Lustre Filesystem ID
    Default: ""
  FSxLustreFilesystemMountName:
    Type: String
    Description: (Optional) Amazon FSx for Lustre Mount Name (required if FSxLustreFilesystemId is provided)
    Default: ""

Resources:

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Ref LaunchTemplateName
      LaunchTemplateData:
        MetadataOptions:
          HttpEndpoint: enabled
          HttpPutResponseHopLimit: 4
          HttpTokens: required
        SecurityGroupIds: !Ref NodeGroupSecurityGroupIds    
        UserData:
          Fn::Base64: !Sub |
            MIME-Version: 1.0
            Content-Type: multipart/mixed; boundary="==MYBOUNDARY=="

            --==MYBOUNDARY==
            Content-Type: text/cloud-config; charset="us-ascii"
            MIME-Version: 1.0

            packages:
            - amazon-efs-utils
            
            runcmd:
            # Mount EFS filesystem as /home
            - mkdir -p /tmp/home
            - rsync -a /home/ /tmp/home
            - echo "${EfsFilesystemId}:/ /home efs tls,_netdev" >> /etc/fstab
            - mount -a -t efs defaults
            - rsync -a --ignore-existing /tmp/home/ /home
            - rm -rf /tmp/home/
            # If provided, mount FSxL filesystem as /shared
            - if [ ! -z "${FSxLustreFilesystemId}" ]; then amazon-linux-extras install -y lustre=latest; mkdir -p /shared; chmod a+rwx /shared; mount -t lustre ${FSxLustreFilesystemId}.fsx.${AWS::Region}.amazonaws.com@tcp:/${FSxLustreFilesystemMountName} /shared; fi

            --==MYBOUNDARY==

Outputs:
  LaunchTemplateId:
    Description: "Launch template Id"
    Value: !Ref LaunchTemplate
  DefaultVersionNumber:
    Description: "Default version number"
    Value: !GetAtt LaunchTemplate.DefaultVersionNumber
  LatestVersionNumber:
    Description: "Latest version number"
    Value: !GetAtt LaunchTemplate.DefaultVersionNumber    
