AWSTemplateFormatVersion: 2010-09-09
Description: Create a launch template to support a compute node group

Parameters:

  LaunchTemplateName:
    Type: String
    Default: "AWSPCS-basic-launch-template"
    Description: Launch template name
  NodeGroupSecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Security group(s).
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: SSH keypair to log into node group instances

Resources:

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Ref LaunchTemplateName
      LaunchTemplateData:
        # Require IMDS v2
        MetadataOptions:
          HttpEndpoint: enabled
          HttpPutResponseHopLimit: 4
          HttpTokens: required
        # Configure SSH keypair
        KeyName: !Ref KeyName
        # Configure node group instance security groups
        SecurityGroupIds: !Ref NodeGroupSecurityGroupIds


Outputs:
  LaunchTemplateId:
    Description: "Launch template Id"
    Value: !Ref LaunchTemplate
  DefaultVersionNumber:
    Description: "Default version number"
    Value: !GetAtt LaunchTemplate.DefaultVersionNumber
  LatestVersionNumber:
    Description: "Latest version number"
    Value: !GetAtt LaunchTemplate.DefaultVersionNumber    
