---
AWSTemplateFormatVersion: 2010-09-09
Description: Create a service role to use with AWS PCS beta

Resources:

  ServicePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
         ManagedPolicyName: AWSPCSServiceRolePolicy
         PolicyDocument:
            Version: 2012-10-17   
            Statement:
              - Sid: PermissionsToCreatePCSNetworkInterfaces
                Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                Resource: arn:aws:ec2:*:*:network-interface/*
                Condition:
                  "Null":
                    aws:RequestTag/AWSPCSManaged: "false"
              - Sid: PermissionsToCreatePCSNetworkInterfacesInSubnet
                Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                Resource:
                  - arn:aws:ec2:*:*:subnet/*
                  - arn:aws:ec2:*:*:security-group/*
              - Sid: PermissionsToManagePCSNetworkInterfaces
                Effect: Allow
                Action:
                  - ec2:DeleteNetworkInterface
                  - ec2:CreateNetworkInterfacePermission
                Resource: "arn:aws:ec2:*:*:network-interface/*"
                Condition:
                  "Null":
                    aws:ResourceTag/AWSPCSManaged: "false"
              - Sid: PermissionsToDescribePCSResources
                Effect: Allow
                Action:
                  - ec2:DescribeSubnets
                  - ec2:DescribeVpcs
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DescribeLaunchTemplates
                  - ec2:DescribeLaunchTemplateVersions
                  - ec2:DescribeInstances
                  - ec2:DescribeInstanceTypes
                  - ec2:DescribeInstanceStatus
                  - ec2:DescribeInstanceAttribute
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeKeyPairs
                  - ec2:DescribeImages
                  - ec2:DescribeImageAttribute
                Resource: "*"
              - Sid: PermissionsToCreatePCSLaunchTemplates
                Effect: Allow
                Action:
                  - ec2:CreateLaunchTemplate
                Resource: "arn:aws:ec2:*:*:launch-template/*"
                Condition:
                  "Null":
                    aws:RequestTag/AWSPCSManaged: "false"
              - Sid: PermissionsToManagePCSLaunchTemplates
                Effect: Allow
                Action:
                  - ec2:DeleteLaunchTemplate
                  - ec2:CreateLaunchTemplateVersion
                  - ec2:DeleteLaunchTemplateVersions
                Resource: "arn:aws:ec2:*:*:launch-template/*"
                Condition:
                  "Null":
                    aws:ResourceTag/AWSPCSManaged: "false"
              - Sid: PermissionsToTerminatePCSManagedInstances
                Effect: Allow
                Action:
                  - ec2:TerminateInstances
                Resource: "arn:aws:ec2:*:*:instance/*"
                Condition:
                  "Null":
                    aws:ResourceTag/AWSPCSManaged: "false"
              - Sid: PermissionsToPassRoleToEC2
                Effect: Allow
                Action: iam:PassRole
                Resource:
                  - arn:aws:iam::*:role/*/AWSPCS*
                  - arn:aws:iam::*:role/AWSPCS*
                  - arn:aws:iam::*:role/aws-pcs/*
                  - arn:aws:iam::*:role/*/aws-pcs/*
                Condition:
                  StringEquals:
                    iam:PassedToService:
                      - ec2.amazonaws.com
              - Sid: PermissionsToControlClusterInstanceAttributes
                Effect: Allow
                Action:
                  - ec2:RunInstances
                  - ec2:CreateFleet
                Resource:
                  - arn:aws:ec2:*::image/*
                  - arn:aws:ec2:*::snapshot/*
                  - arn:aws:ec2:*:*:subnet/*
                  - arn:aws:ec2:*:*:network-interface/*
                  - arn:aws:ec2:*:*:security-group/*
                  - arn:aws:ec2:*:*:volume/*
                  - arn:aws:ec2:*:*:key-pair/*
                  - arn:aws:ec2:*:*:launch-template/*
                  - arn:aws:ec2:*:*:placement-group/*
                  - arn:aws:ec2:*:*:capacity-reservation/*
                  - arn:aws:resource-groups:*:*:group/*
                  - arn:aws:ec2:*:*:fleet/*
              - Sid: PermissionsToProvisionClusterInstances
                Effect: Allow
                Action:
                  - ec2:RunInstances
                  - ec2:CreateFleet
                Resource:
                  - "arn:aws:ec2:*:*:instance/*"
                Condition:
                  "Null":
                    aws:RequestTag/AWSPCSManaged: "false"
              - Sid: PermissionsToTagPCSResources
                Effect: Allow
                Action:
                  - ec2:CreateTags
                Resource:
                  - "*"
                Condition:
                  StringEquals:
                    ec2:CreateAction:
                      - RunInstances
                      - CreateLaunchTemplate
                      - CreateFleet
                      - CreateNetworkInterface
              - Sid: PermissionsToPublishMetrics
                Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource:
                  - "*"
                Condition:
                  StringEquals:
                    cloudwatch:namespace:
                      - AWS/PCS

  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
           - !Ref ServicePolicy
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - pcs.amazonaws.com
        Version: 2012-10-17
      RoleName: AWSPCSServiceRole
