AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an FSx for OpenZFS filesystem and a client security group for access to the filesystem

### Stack metadata
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Filesystem Options
        Parameters:
          - Capacity
          - Compression
          - ThroughputCapacity
          - RecordSize
      - Label:
          default: Networking and Access
        Parameters:
          - VpcId
          - SubnetId

Parameters:
  VpcId:
    Description: VPC where you will deploy the FSx filesystem
    Type: AWS::EC2::VPC::Id
  SubnetId:
    Description: Subnet where you will deploy the FSx filesystem (must be in same VPC)
    Type: AWS::EC2::Subnet::Id
  Capacity:
    Description: Storage capacity (GiB)
    Type: Number
    Default: 256
  Compression:
    Description: Data compression type
    Type: String
    AllowedValues:
      - "LZ4"
      - "ZSTD"
      - "NONE"
    Default: "LZ4"
  RecordSize:
    Description: Record size in KiB for the root volume
    Type: Number
    Default: 128
    AllowedValues:
      - 4
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
      - 512
      - 1024
  ThroughputCapacity:
    Description: Throughput capacity for the filesystem (MBps)
    Type: Number
    Default: 64
    AllowedValues:
         - 64
         - 128
         - 256
         - 512
         - 1024
         - 2048
         - 3072
         - 4096

Resources:
 
  # Security group
  ZfsServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: 'Allows traffic to FSx for OpenZFS filesystem'
      GroupName: !Sub '${AWS::StackName}-fsxzfs-security-group'
      VpcId: !Ref VpcId

  # Clients join this group for access to an FSx for OpenZFS filesystem or volume
  ZfsClientSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Clients join this group for access to FSx for OpenZFS filesystem or volume'
      GroupName: !Sub '${AWS::StackName}-fsxzfs-client-security-group'
      VpcId: !Ref VpcId

  ZfsServerSGInboundRule2049tcp:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      IpProtocol: tcp
      Description: Allow incoming TCP connection from clients to NFS server daemon on port 2049
      FromPort: 2049
      ToPort: 2049
      GroupId: !Ref ZfsServerSG
      SourceSecurityGroupId: !Ref ZfsClientSG
  ZfsServerSGInboundRule2049udp:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      IpProtocol: udp
      Description: Allow incoming UDP connection from clients to NFS server daemon on port 2049
      FromPort: 2049
      ToPort: 2049
      GroupId: !Ref ZfsServerSG
      SourceSecurityGroupId: !Ref ZfsClientSG
  ZfsServerSGInboundRule111tcp:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      IpProtocol: tcp
      Description: Allow incoming TCP remote procedure call from client to NFS server on port 111
      FromPort: 111
      ToPort: 111
      GroupId: !Ref ZfsServerSG
      SourceSecurityGroupId: !Ref ZfsClientSG
  ZfsServerSGInboundRule111udp:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      IpProtocol: udp
      Description: Allow incoming UDP remote procedure call from client to NFS server on port 111
      FromPort: 111
      ToPort: 111
      GroupId: !Ref ZfsServerSG
      SourceSecurityGroupId: !Ref ZfsClientSG
  ZfsServerSGInboundRule20001tcp:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      IpProtocol: tcp
      Description: Allow incoming TCP traffic from client to NFS mount, status monitor, and lock daemons (ports 20001-20003)
      FromPort: 20001
      ToPort: 20003
      GroupId: !Ref ZfsServerSG
      SourceSecurityGroupId: !Ref ZfsClientSG
  ZfsServerSGInboundRule20001udp:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      IpProtocol: udp
      Description: Allow incoming UDP traffic from client to NFS mount, status monitor, and lock daemons (ports 20001-20003
      FromPort: 20001
      ToPort: 20003
      GroupId: !Ref ZfsServerSG
      SourceSecurityGroupId: !Ref ZfsClientSG
  ZfsServerSGOutboundRuleClientSGAll:
    Type: 'AWS::EC2::SecurityGroupEgress'
    Properties:
      Description: Allow egress to client from server
      IpProtocol: -1
      GroupId: !Ref ZfsServerSG
      DestinationSecurityGroupId: !Ref ZfsClientSG
  ZfsClientSGOutboundRuleServerSGAll:
    Type: 'AWS::EC2::SecurityGroupEgress'
    Properties:
      Description: Allow egress to server from client
      IpProtocol: -1
      GroupId: !Ref ZfsClientSG
      DestinationSecurityGroupId: !Ref ZfsServerSG


  FSxOpenZFSFilesystem:
    Type: AWS::FSx::FileSystem
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      FileSystemType: OPENZFS
      StorageType: SSD
      StorageCapacity: !Ref Capacity
      SecurityGroupIds:
        - !Ref ZfsServerSG
      SubnetIds:
        - !Ref SubnetId
      OpenZFSConfiguration:
        DeploymentType: SINGLE_AZ_1
        ThroughputCapacity: !Ref ThroughputCapacity
        RootVolumeConfiguration:
          DataCompressionType: !Ref Compression
          RecordSizeKiB: !Ref RecordSize
          NfsExports:
            - ClientConfigurations:
                - Clients: "*"
                  Options: ["crossmnt", "sync", "rw"]

Outputs:
  FSxOpenZFSFilesystemId:
    Description: The ID of the FSxOpenZFS filesystem
    Value: !Ref FSxOpenZFSFilesystem
    Export:
      Name: !Sub ${AWS::StackName}-FSxOpenZFSFilesystemId
  FSxOpenZFSRootVolumeId:
    Description: The root volume ID for the FSxOpenZFS filesystem
    Value: !GetAtt FSxOpenZFSFilesystem.RootVolumeId
    Export:
      Name: !Sub ${AWS::StackName}-FSxOpenZFSRootVolumeId
  FSxOpenZFSSecurityGroupId:
    Description: Clients join this group for access to the FSx for OpenZFS filesystem or mount
    Value: !Ref ZfsClientSG
    Export:
      Name: !Sub ${AWS::StackName}-FSxOpenZFSSecurityGroupId
