AWSTemplateFormatVersion: 2010-09-09
Description: Create Log Delivery bindings for PCS Cluster scheduler logs and job completion logs to CloudWatch. 

Parameters: 
  PCSClusterId: 
    Type: String
    Description: "Enter PCS Cluser ID (format: pcs_XXXXXXXXXX)"
    AllowedPattern: "pcs_[A-Za-z0-9]{10}"
    ConstraintDescription: "Must match pattern: pcs_XXXXXXXXXX where X can be letters or numbers"

Resources: 
  PCSSchedulerLogDeliverySource:
    Type: AWS::Logs::DeliverySource
    Properties:
      LogType: PCS_SCHEDULER_LOGS
      ResourceArn: !Sub "arn:${AWS::Partition}:pcs:${AWS::Region}:${AWS::AccountId}:cluster/${PCSClusterId}"
      Name: !Sub "${PCSClusterId}-cluster-scheduler-logs-source"

  PCSSchedulerLogCloudwatchDeliveryDestination:
    Type: AWS::Logs::DeliveryDestination
    #DependsOn: PCSSchedulerLogDeliveryGroup
    Properties:
      DestinationResourceArn: !GetAtt PCSSchedulerLogDeliveryGroup.Arn
      Name: !Sub "${PCSClusterId}-cluster-scheduler-cw-logs-destination"

  PCSSchedulerLogDelivery:
    Type: AWS::Logs::Delivery
    Properties:
      DeliveryDestinationArn: !GetAtt PCSSchedulerLogCloudwatchDeliveryDestination.Arn
      DeliverySourceName: !Ref PCSSchedulerLogDeliverySource
    
  # Log groups prefixed with '/aws/vendedlogs/' will be created automatically.
  # Other log groups must be created prior to setting up a log delivery. 
  # We opt to create groups regardless of destination. 
  #############################
  PCSSchedulerLogDeliveryGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: RetainExceptOnCreate
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupClass: STANDARD
      LogGroupName: !Sub "/aws/vendedlogs/pcs/cluster/PCS_SCHEDULER_LOGS/${PCSClusterId}"
      RetentionInDays: 60


  PCSJobCompLogDeliverySource:
    Type: AWS::Logs::DeliverySource
    Properties:
      LogType: PCS_JOBCOMP_LOGS
      ResourceArn: !Sub "arn:${AWS::Partition}:pcs:${AWS::Region}:${AWS::AccountId}:cluster/${PCSClusterId}"
      Name: !Sub "${PCSClusterId}-cluster-jobcomp-logs-source"

  PCSJobCompLogCloudwatchDeliveryDestination:
    Type: AWS::Logs::DeliveryDestination
    #DependsOn: PCSJobCompLogDeliveryGroup
    Properties:
      DestinationResourceArn: !GetAtt PCSJobCompLogDeliveryGroup.Arn
      Name: !Sub "${PCSClusterId}-cluster-jobcomp-cw-logs-destination"

  PCSJobCompLogDelivery:
    Type: AWS::Logs::Delivery
    Properties:
      DeliveryDestinationArn: !GetAtt PCSJobCompLogCloudwatchDeliveryDestination.Arn
      DeliverySourceName: !Ref PCSJobCompLogDeliverySource
    
  # Log groups prefixed with '/aws/vendedlogs/' will be created automatically.
  # Other log groups must be created prior to setting up a log delivery. 
  # We opt to create groups regardless of destination. 
  #############################
  PCSJobCompLogDeliveryGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: RetainExceptOnCreate
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupClass: STANDARD
      LogGroupName: !Sub "/aws/vendedlogs/pcs/cluster/PCS_JOBCOMP_LOGS/${PCSClusterId}"
      RetentionInDays: 60

Outputs: 

  PCSCluster: 
    Description: "ARN of the PCS Cluster (Source)"
    Value: !Select [0, !GetAtt PCSSchedulerLogDeliverySource.ResourceArns]
    
  PCSSchedulerLogDeliveryDestination: 
    Description: "ARN of the CloudWatch LogGroup for Scheduler Logs (Destination)"
    Value: !GetAtt PCSSchedulerLogCloudwatchDeliveryDestination.Arn

  PCSJobCompLogDeliveryDestination: 
    Description: "ARN of the CloudWatch LogGroup for Job Completion Logs (Destination)"
    Value: !GetAtt PCSJobCompLogCloudwatchDeliveryDestination.Arn