AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Instance Profile for use with AWS PCS

Resources:

  pcsComputeNodeGroupRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "PCS-Compute-Node-Role"
      Description: ""
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - pcs:RegisterComputeNodeGroupInstance
                Effect: Allow
                Resource: "*"
          PolicyName: RegisterComputeNodeGroup

  pcsComputeNodeGroupInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: ComputeNodeGroupInstanceProfile
      Roles:
        - !Ref pcsComputeNodeGroupRole

Outputs:
  InstanceProfileArn:
    Value: {"Fn::GetAtt" : [!Ref pcsComputeNodeGroupInstanceProfile, "Arn"] }

