AWSTemplateFormatVersion: 2010-09-09
Description: Create a launch template to support a compute node group


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      = Label:
          default: Launch Template
        Parameters:
          - LaunchTemplateName
      - Label:
          default: Networking and Security
        Parameters:
          - NodeGroupSubnetId
          - NodeGroupSecurityGroupIds
          - KeyName
      - Label:
          default: Instance
        Parameters:
          - AmiId
      - Label:
          default: Filesystems
        Parameters:
          - EfsFilesystemId
          - HostMountPoint

Parameters:

  LaunchTemplateName:
    Type: String
  NodeGroupSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet
  NodeGroupSecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Security groups (must allow access to EFS filesystem)
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: SSH keypair to log into node group instances
  AmiId:
    Type: String
    Description: Optional AMI ID - leave blank if using a service-optimized AMI.
  EfsFilesystemId:
    Type: String
    Description: Amazon EFS Filesystem ID (must be accessible to NodeGroupSubnetId)
  HostMountPoint:
    Type: String
    Description: Mount path on the host
    Default: "/shared"

Conditions:
  SpecifyAmi: !Not [ !Equals [!Ref AmiId, ""] ]

Resources:

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Ref LaunchTemplateName
      LaunchTemplateData:
        KeyName: !Ref KeyName
        ImageId:
          !If
          - SpecifyAmi
          - !Ref AmiId
          - !Ref "AWS::NoValue"
        NetworkInterfaces:
          - DeviceIndex: 0
            SubnetId: !Ref NodeGroupSubnetId
            Groups: !Ref NodeGroupSecurityGroupIds
        UserData:
          Fn::Base64: !Sub |
            MIME-Version: 1.0
            Content-Type: multipart/mixed; boundary="==MYBOUNDARY=="

            --==MYBOUNDARY==
            Content-Type: text/x-shellscript; charset="us-ascii"
            MIME-Version: 1.0

            #!/bin/bash -xe
            # Mount EFS on AL2 or other Fedora-adjacent OS
            echo "Mounting ${EfsFilesystemId} at ${HostMountPoint}"
            # yum install -y amazon-efs-utils
            # yum install -y nfs-utils
            mkdir -p "${HostMountPoint}"
            test -f "/sbin/mount.efs" && printf "\n${EfsFilesystemId}:/ ${HostMountPoint} efs iam,tls,_netdev\n" >> /etc/fstab || printf "\n${EfsFilesystemId}.efs.${AWS::Region}.amazonaws.com:/ ${HostMountPoint} nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport,_netdev 0 0\n" >> /etc/fstab
            test -f "/sbin/mount.efs" && printf "\n[client-info]\nsource=liw\n" >> /etc/amazon/efs/efs-utils.conf
            retryCnt=15; waitTime=30; while true; do mount -a -t efs,nfs4 defaults; if [ $? = 0 ] || [ $retryCnt -lt 1 ]; then echo File system mounted successfully; break; fi; echo File system not available, retrying to mount.; ((retryCnt--)); sleep $waitTime; done;

            --==MYBOUNDARY==

Outputs:
  LaunchTemplateId:
    Description: "Launch template Id"
    Value: !Ref LaunchTemplate
  DefaultVersionNumber:
    Description: "Default version number"
    Value: !GetAtt LaunchTemplate.DefaultVersionNumber
  LatestVersionNumber:
    Description: "Latest version number"
    Value: !GetAtt LaunchTemplate.DefaultVersionNumber    
