AWSTemplateFormatVersion: 2010-09-09
Description: Create a launch template to support a PCS compute node group mounting FSx for Lustre


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Launch Template
        Parameters:
          - LaunchTemplateName
      - Label:
          default: Networking
        Parameters:
          - NodeGroupSubnetId
      - Label:
          default: Security
        Parameters:
          - KeyName
          - VpcSecurityGroupId
          - EfsClientSecurityGroupId
          - FSxLustreClientSecurityGroupId
          - InboundAccessSecurityGroupId
      - Label:
          default: Instance
        Parameters:
          - AmiId
      - Label:
          default: Filesystems
        Parameters:
          - EfsFilesystemId
          - EfsHostMountPoint
          - FSxLustreFilesystemId
          - FSxLustreHostMountPoint

Parameters:

  LaunchTemplateName:
    Type: String
  NodeGroupSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet
  VpcSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security allowing access within the VPC
  InboundAccessSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group controlling inbound SSH access
  FSxLustreClientSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group allowing access to the FSx for Lustre filesystem
  EfsClientSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group allowing access to the EFS filesystem
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: SSH keypair to log into node group instances
  AmiId:
    Type: String
    Description: Optional AMI ID - leave blank if using a service-optimized AMI.
  FSxLustreFilesystemId:
    Type: String
    Description: Amazon FSx for Lustre Filesystem ID (must be accessible to NodeGroupSubnetId)
  FSxLustreHostMountPoint:
    Type: String
    Description: Lustre mount path on the host
    Default: "/scratch"
  EfsFilesystemId:
    Type: String
    Description: Amazon EFS Filesystem ID (must be accessible to NodeGroupSubnetId)
  EfsHostMountPoint:
    Type: String
    Description: EFS mount path on the host
    Default: "/home"

Conditions:
  SpecifyAmi: !Not [ !Equals [!Ref AmiId, ""] ]

Resources:

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Ref LaunchTemplateName
      LaunchTemplateData:
        MetadataOptions:
          HttpEndpoint: enabled
          HttpPutResponseHopLimit: 4
          HttpTokens: required
        KeyName: !Ref KeyName
        ImageId:
          !If
          - SpecifyAmi
          - !Ref AmiId
          - !Ref "AWS::NoValue"
        NetworkInterfaces:
          - DeviceIndex: 0
            SubnetId: !Ref NodeGroupSubnetId
            Groups:
              - !Ref VpcSecurityGroupId
              - !Ref InboundAccessSecurityGroupId
              - !Ref FSxLustreClientSecurityGroupId
              - !Ref EfsClientSecurityGroupId
        UserData:
          Fn::Base64: !Sub |
            MIME-Version: 1.0
            Content-Type: multipart/mixed; boundary="==MYBOUNDARY=="

            --==MYBOUNDARY==
            Content-Type: text/cloud-config; charset="us-ascii"
            MIME-Version: 1.0

            runcmd:
            - amazon-linux-extras install -y lustre=latest
            - mkdir -p ${FSxLustreHostMountPoint}
            - mount -t lustre ${FSxLustreFilesystemId}.fsx.${AWS::Region}.amazonaws.com@tcp:fsx ${FSxLustreHostMountPoint}
            - chmod a+rxw "${FSxLustreHostMountPoint}"

            --==MYBOUNDARY==
            Content-Type: text/cloud-config; charset="us-ascii"
            MIME-Version: 1.0

            packages:
            - amazon-efs-utils
            
            runcmd:
            - mkdir -p ${EfsHostMountPoint}
            - echo "${EfsFilesystemId}:/ ${EfsHostMountPoint} efs tls,_netdev" >> /etc/fstab
            - mount -a -t efs defaults
            - chmod a+rxw "${EfsHostMountPoint}"

            --==MYBOUNDARY==--

Outputs:
  LaunchTemplateId:
    Description: "Launch template Id"
    Value: !Ref LaunchTemplate
  DefaultVersionNumber:
    Description: "Default version number"
    Value: !GetAtt LaunchTemplate.DefaultVersionNumber
  LatestVersionNumber:
    Description: "Latest version number"
    Value: !GetAtt LaunchTemplate.DefaultVersionNumber    
