AWSTemplateFormatVersion: 2010-09-09
Description: Creates a security group to enable EFA on a node group

Parameters:
  VpcId:
    Description: VPC where the PCS Cluster will be deployed
    Type: 'AWS::EC2::VPC::Id'

Resources:

  PcsEfaSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Support ComputeNodeGroup EFA
      GroupName: !Join ['-', ['pcs-efa-compute-nodes-sg', !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
      VpcId: !Ref VpcId

  EfaSecurityGroupInboundRule:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      IpProtocol: '-1'
      Description: Allow incoming connection to EFA from members of security group
      GroupId: !Ref PcsEfaSecurityGroup
      SourceSecurityGroupId: !Ref PcsEfaSecurityGroup

  EfaSecurityGroupOutboundRule:
    Type: 'AWS::EC2::SecurityGroupEgress'
    Properties:
      IpProtocol: '-1'
      Description: Allow outgoing connection from EFA to members of security group
      GroupId: !Ref PcsEfaSecurityGroup
      DestinationSecurityGroupId: !Ref PcsEfaSecurityGroup

Outputs:
  NodeSecurityGroupId:
    Description: Security group enabling EFA access on EC2 instances
    Value: !Ref PcsEfaSecurityGroup
