AWSTemplateFormatVersion: 2010-09-09
Description: Creates a security group that allows inbound SSH from public internet for PCS login node instances

Parameters:
  VpcId:
    Description: VPC where the PCS Cluster will be deployed
    Type: 'AWS::EC2::VPC::Id'
  AllowedIps:
    Description: CIDR-formatted IP range for SSH access to node group instances
    Type: String
    Default: 0.0.0.0/0
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'

Resources:
  PcsSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Support ComputeNodeGroup instance SSH
      GroupName: !Join ['-', ['pcs-login-nodes-sg', !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
      VpcId: !Ref VpcId
      SecurityGroupIngress:
           - IpProtocol: 'tcp'
             CidrIp: !Ref AllowedIps
             FromPort: 22
             ToPort: 22
             Description: Allow inbound SSH
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic
          IpProtocol: '-1'

Outputs:
  NodeSecurityGroupId:
    Description: Security group allowing access to EC2 instances
    Value: !Ref PcsSecurityGroup
